name: Test, Build and Deploy

on: [push]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v5
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod download

      - name: Test
        run: go test ./...

      - name: Build
        run: make build

  continuous-delivery:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    name: Push Docker Image
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: Staffbase/gitops-github-action
          ref: v1
          token: ${{ secrets.GITOPS_TOKEN }}
          path: .github/gitops

      - name: GitOps (build, push and deploy a new Docker image)
        uses: ./.github/gitops
        with:
          dockerregistry: docker.io
          dockerusername: ${{ secrets.DOCKER_USERNAME }}
          dockerpassword: ${{ secrets.DOCKER_PASSWORD }}
          dockerimage: frittenbude/syseleven-exporter
